"""Deterministic B24 wrapper examples with public-safe sample payloads."""
from __future__ import annotations
from typing import Any, Callable
from memory_lab.wrappers.bounded_tools import build_supplied_prompt_package, evaluate_supplied_circuit_state, rank_supplied_context_candidates, score_supplied_ingestion_signals, validate_supplied_structured_response

def sample_payloads() -> dict[str, dict[str, Any]]:
    candidate={"item_id":"sample-public-note-1","text":"B24 bounded wrappers process only supplied public-safe samples and expose explicit non-claims.","snippet":"B24 bounded wrappers process only supplied public-safe samples.","purpose_text":"bounded wrapper contract evidence","domain":"public_release_governance","tags":["b24","wrapper","contract"],"source_metadata":{"source":"public_sample_fixture","license":"sample"},"extraction_confidence":0.86,"domain_confidence":0.82,"hub_signal":0.74,"tag_signal":0.79,"knn_score":0.0,"knn_ready":False,"ingestion_score":0.81,"tier":"sample","circuit_state":"closed","executor_limitations":["sample_only"],"validator_limitations":["structural_only"],"risk_level":"low","recency_rank":0.5}
    return {"validate_supplied_structured_response":{"response":{"status":"ok","answer":"Sample answer grounded only in supplied evidence.","confidence":0.72,"claims":[{"claim":"B24 examples are supplied samples.","evidence_ids":[1]}]},"evidence_count":1},"score_supplied_ingestion_signals":{"extraction_confidence":0.86,"domain_confidence":0.82,"hub_confidence":0.74,"tag_confidence":0.79,"chunk_quality":0.88,"chunk_composite":0.84,"embedding_admin_ready":False,"knn_ready":False,"risk_flags":[],"completeness_flags":["has_text","has_domain","has_tags"],"signal_metadata":{"fixture":"b24_public_sample"}},"evaluate_supplied_circuit_state":{"events":[{"event_type":"success","timestamp":100.0,"reason":"sample event"}],"now":120.0,"initial_state":"closed","config":{"failure_threshold":3,"degraded_threshold":2,"window_seconds":60.0,"open_duration_seconds":300.0}},"rank_supplied_context_candidates":{"query":"bounded wrapper contract","purpose":"cite","candidates":[candidate],"limit":3},"build_supplied_prompt_package":{"query":"bounded wrapper contract","purpose":"cite","candidates":[candidate],"limit":3,"max_candidates":2,"max_context_chars":1600,"snippet_chars":300}}

def sample_responses() -> dict[str, dict[str, Any]]:
    payloads=sample_payloads(); tools: dict[str, Callable[[dict[str, Any]], dict[str, Any]]] = {"validate_supplied_structured_response":validate_supplied_structured_response,"score_supplied_ingestion_signals":score_supplied_ingestion_signals,"evaluate_supplied_circuit_state":evaluate_supplied_circuit_state,"rank_supplied_context_candidates":rank_supplied_context_candidates,"build_supplied_prompt_package":build_supplied_prompt_package}
    return {name: tools[name](payloads[name]) for name in tools}
